# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 246)
        MainWindow.setStyleSheet("background: #582841;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 441, 31))
        self.lineEdit.setPlaceholderText("Enter the link...")
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #F99E4C;\n"
"    outline: none;\n"
"    color: #F99E4C;\n"
"    padding: 5px;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 211, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #F99E4C;\n"
"    background: #582841;\n"
"    border: 1px solid #F99E4C;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #582841;\n"
"    background: #F99E4C;\n"
"    border: 1px solid #F99E4C;\n"
"    transition: 0.6s;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 50, 211, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: #F99E4C;\n"
"    background: #582841;\n"
"    border: 1px solid #F99E4C;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #582841;\n"
"    background: #F99E4C;\n"
"    border: 1px solid #F99E4C;\n"
"    transition: 0.6s;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 441, 91))
        self.label.setStyleSheet("QLabel {\n"
"    background: #582841;\n"
"    color: #F99E4C;\n"
"    border: 1px solid #F99E4C;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Folder"))
        self.pushButton_2.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
